### ISSUE TITLE
Provide the source code of the application

### ISSUE THREAD

**Issue by gyger** [alyrefay/GCSim#1]
Hej,
I was wondering if you plan to provide the source code of the application?

**Comment by AlyAbdou** [comment]
I have added sample code to the directory. However, I believe the whole app is simple and not even optimised for best performance. My intention was only to create executable for people who are not able to code themselves and don't have access to simulation software (as I indicated in the attached document with the app). If you need I can provide further code or direct you to the videos I depended on in creating the application
